/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:cb7c468d-c993-4833-9a4b-8137ae073d62",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8dUKH8RhO",
    "aws_user_pools_web_client_id": "57o4sb53accjrvse0j8049frev",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://7ozn5quywnavpiccciise5spxq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7hhm7waiqvfgnga2jczvqho5qm",
    "aws_user_files_s3_bucket": "amplifynexttemplate8554dd3501474916b1ea47c27d7460c83-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
